baseURL = 'https://emilioblacksmith.github.io/Blog/'
defaultContentLanguage = "en"
languageCode = "en"

title = "Emilio Blacksmith Blog"

theme = "gokarna"

enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[markup.goldmark.renderer]
unsafe= true

[params]
  footer = "EmilioBlacksmith"
  description = "Howdy 🤠, I make development fun to watch (sometimes...)"
  showPostsOnHomePage = "recent"
  avatarURL = "images/profile.webp"
  AvatarAltText = "avatar"
  avatarSize = "size-xl"
  accentColor = "#0080ff"
  favicon = true
  
  svg = true
  author = "Emilio Blacksmith with Hugo"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  metaKeywords = ["blog", "emilioblacksmith", "gamedev", "webdev","softdev"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "./"
    weight = 1

  [[menu.main]]
    name = "Website"
    pre = "<span data-feather='globe'></span>"
    url = "https://emilioblacksmith.github.io/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "./posts/"
    weight = 3

    [[menu.main]]
    identifier = "youtube"
    pre = "<span data-feather='youtube'></span>"
    url = "https://www.youtube.com/@EmilioBlacksmith"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/EmilioBlacksmith"
    weight = 5

  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/emilioblacksmith/"
    weight = 6
  
  [[menu.main]]
    identifier = "instagram"
    pre = "<span data-feather='instagram'></span>"
    url = "https://www.instagram.com/emilioblacksmith/"
    weight = 7
  
  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 8


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
